In [0]:
import numpy as np


In [0]:
X=np.array([[1],[2],[3],[4]]) ##input array
print(X.shape)

(4, 1)


In [0]:
y=np.array([1,4,9,16])#output array

In [0]:
bias=np.ones(len(X)) #bias array
  

In [0]:
bias=np.reshape(bias,(4,1)) #reshaping to column vector

In [0]:
X=np.append(bias,X,axis=1) #adding bias to input array

In [100]:
X.shape


(4, 2)

In [0]:
theta=np.zeros((X.shape[1]))#initializing parameters to zero

In [0]:
theta=np.reshape(theta,(2,1)) #reshaping to column vector

In [114]:
#calculating the cost function
def cost_funct(X,y,theta):
  j=np.sum((X.dot(theta)-y)**2)/len(X)
  return j
print(cost_funct(X,y,theta))

88.5


In [0]:
alpha=0.01#learning rate
#calculating the gradient
def grad(X,y,theta,iterations):
  cost_hist=np.empty(iterations)
  for i in range(iterations):
    h=X.dot(theta)
    loss=h-y
    gradient=X.T.dot(loss)/len(X)
    theta=theta-alpha*gradient
    cost=cost_funct(X,y,theta)
    cost_hist=np.append(cost_hist,cost)
  return theta,cost_hist
new_theta,finalcost=grad(X,y,theta,1000)

In [202]:
print(new_theta)
print(finalcost[-1])

[0.17056043 3.24062606]
5.465423732806942


In [0]:
y_pred=X.dot(new_theta) #predicting the output

In [207]:
y_pred

array([ 0.88599736,  5.4293264 ,  9.97265543, 14.51598447])

In [208]:
X_new=np.array([[5],[6],[7]])
xnb=np.ones(len(X_new))
xnb=np.reshape(xnb,X_new.shape)
X_new=np.append(xnb,X_new,axis=1)
X_new

array([[1., 5.],
       [1., 6.],
       [1., 7.]])

In [209]:
y_pred2=X_new.dot(new_theta)
y_pred2

array([19.0593135 , 23.60264253, 28.14597157])

USING SCIKIT-LEARN


In [0]:
from sklearn.linear_model import LinearRegression

In [181]:
reg=LinearRegression()

reg.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
X_new2=np.array([[5],[6],[7]])
y_pred=reg.predict(X_new)

In [184]:
y_pred

array([20., 25., 30.])

In [185]:
reg.coef_

array([0., 5.])